config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'   
 end
  root "homes#index"
  match 'questions/filter_form' => 'questions#question_filter_form', as: :question_filter_form, via: [:get, :post]
  get 'add_new_fields', to: 'questions#add_new_fields'
  get 'questions/print_page', to: 'questions#print_page', as: :question_print_page
end

app/models/ability.rb
class Ability
  include CanCan::Ability
    def initialize(user)
      user ||= User.new #guest user
    if user.type == "Admin"
      can :manage, :all
    end
    if user.type == "Editor"
      can :manage, Question
      can :manage, Technology
      can :read, [Editor]
      can [:update, :read], Editor, id: user.id
    end
    if user.type == "Viewer"
      can :read, Question
      can [:update, :read], Viewer, id: user.id
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/editor.rb
class Editor < User
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question, :uniqueness => true
  validates :question, :answer, :technology_id, :marks, presence: true
  belongs_to :technology
  def approve!
    update(status: true)
end
end
 

app/models/technology.rb
class Technology < ApplicationRecord
    validates :name, :uniqueness => true
    has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :email, presence: true
  validates :password, :password_confirmation, presence: true, on: :create
  validates :password, confirmation: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable
    # roles
    def admin?
      type == 'Admin'
    end
    def viewer?
      type == 'Viewer'
    end
    def editor?
      type == 'Editor'
    end 
  end

app/models/viewer.rb
class Viewer < User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:new, :create]
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :type, :email, :password, :password_confirmation)}
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
    end
    def after_sign_in_path_for(resource)
      resource.admin? ? admin_admins_path : admin_questions_path
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def question_filter_form
    $technologies = Technology.all
    @question = params[:questions]
  end
  def add_new_fields
    respond_to do |format|
        format.html {}
        format.js
    end
  end
  def question_print_page
    respond_to do |format|
        format.html {}
        format.js
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected
      def update_resource(resource, params)
      # Require current password if user is trying to change password.
      return super if params["password"]&.present?
      # Allows user to update registration information without password.
      resource.update_without_password(params.except("current_password"))
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/_navbar.html.erb
<% if user_signed_in? %>
 <span class="nav-item float-end m-5 mt-2">
    <%= link_to 'logout', destroy_user_session_path%>
  </span>
<% else %>
  <span class="nav-item float-end m-5 mt-2">
    <%= link_to 'Sign in', new_user_session_path, class: "nav-link"%>
  </span>
<% end %>

app/views/homes/index.html.erb
<%= render partial: 'navbar' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestionAnswers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success" id="flash"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger" id="flash"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_attr_form.html.erb
<tr>
    <td style="text-align:center;">Select Tecnology: </td>
    <td><%= select_tag 'questions[][tech_id]', options_for_select($technologies.collect{ |u| [u.name, u.id] }), class: "form-control", :include_blank => false, :prompt => 'Select Technology'%></td>
    <td><%= text_field_tag 'questions[][range]', nil, :required => false, class: "form-control", placeholder: 'How many questions?'%></td>
</tr>

app/views/questions/add_new_fields.js.erb
$('#add_new_fields').append("<%= escape_javascript render('attr_form') %>");

app/views/questions/print_page.html.erb
<!DOCTYPE html>
<html lang="en">
<div class="container">
<body>
<h4 style="text-align: center;">INTERVIEW TEST</h4>
<h5>To be filled by candidate:</h5>
<table class="table table-bordered">
    <tr>
        <td colspan="2">Candidate Name: </td>
        <td colspan="2">Applied For: </td>
    </tr>
    <tr>
        <td colspan="2">Current Company: </td>
        <td colspan="2">Current Salary: </td>
    </tr>
    <tr>
        <td colspan="2">Expected Salary: </td>
        <td colspan="2">Expected Joining Date: </td>
    </tr>
    <tr>
        <td colspan="3"><h5>For office use only:</h5></td>
    </tr>
    <tr>
        <td colspan="2">Test Start & End Time: </td>
        <td colspan="2">Test Checked By: </td>
    </tr>
    <tr>
    <% if params[:questions].present?%>
        <% params[:questions].each do |question|%>
            <% if question[:tech_id].present? && question[:range].present? && params[:marks_range_to].present? && params[:marks_range_from].present?%>
            <% questions = Question.where(technology_id: question[:tech_id]).where(marks: params[:marks_range_from]..params[:marks_range_to]).where(status: true).limit(question[:range]).order('RAND()') %>
                <% questions.group_by{|q| q.technology_id}.each do |a|%>
                    <% tech = a[0]%>
                    <%tec = Technology.where(id: tech)%>
                    <%tec.each do |te|%>
                <td class="spacing">
                    <%= te.name%>
                <%end%>
               <span>/<%= a[1].sum(&:marks)%></span>
                </td>
                <%end%>
        <%end%>
        <%end%>
    <%end%>
    </tr>
    <tr>
        <td colspan="6">
            <table class="table table-bordered">
                <tr>
                   <td>Remarks</td>
                </tr>
                <tr>
                    <td></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<% if params[:questions].present?%>
<table class="table table-borderless m-0">
    <% params[:questions].each do |question|%>
        <% if question[:tech_id].present? && question[:range].present? && params[:marks_range_to].present? && params[:marks_range_from].present?%>
            <% questions = Question.where(technology_id: question[:tech_id]).where(marks: params[:marks_range_from]..params[:marks_range_to]).where(status: true).limit(question[:range]).order('RAND()') %>
                <tr { style = "border-bottom: 0.2rem solid black;" }>
                        <%tech = question[:tech_id]%>
                        <% @query1 = Technology.where(id: tech)%>
                        <% @query1.each do |f| %>
                        <th><%= f.name%></th>
                        <%end%>
                <tr>
            <% questions.each do |q| %>
                <tr>
                    <td>
                        QID<%= q.id%>:
                        <td><%= ques = q.question.html_safe%>
                        <%ques.capitalize%>
                        <%ques.tr(',',' ')%>
                        </td>
                    </td>
                    <td>(<%= q.marks.to_i%>)</td>
                </tr>
            <% end %>
        <% end %>
    <%end%>
</table>
<%end%>
</body>
</div>
</html>

app/views/questions/question_filter_form.html.erb
<div class="container">
    <center>
        <h3 class=" p-5">
            SELECT QUESTIONS
        </h3>
    </center>
    <%= form_tag question_print_page_path , :method => :get do |f| %>
    <table class="table table-borderless">
        <thead id="add_new_fields">
        <tr>
            <td style="text-align:center;">Select Tecnology: </td>
            <td><%= select_tag 'questions[][tech_id]', options_for_select($technologies.collect{ |u| [u.name, u.id] }), class: "form-control", :include_blank => false, :prompt => 'Select Technology'%></td>
            <td><%= text_field_tag 'questions[][range]', nil, :required => false, class: "form-control", placeholder: 'How many questions?'%></td>
        </tr>
        </thead>
        <tr>
            <td colspan=3><%= link_to "Add More Technology", add_new_fields_path, remote: true, class: "btn btn-primary btn-sm float-end"%></td>
        </tr>
        <tbody>
        <tr>
            <td style="text-align:center;">Select Marks Range: </td>
            <td><%= text_field_tag 'marks_range_from', value=2, placeholder: 'From', class: "form-control"%></td>
            <td><%= text_field_tag 'marks_range_to', value=5, placeholder: 'To', class: "form-control"%></td>
        </tr>

       </tbody>
    </table>
    <p style="text-align: center;"> 
        <%= submit_tag 'Filter', class: "btn btn-success m-5"%>
    </p>
    <% end %>